'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import { useAssignmentStore } from '@/store/assignmentStore';
import { getAssignment, regenerateAssignment } from '@/lib/api';
import { QuestionPaper } from '@/components/QuestionPaper';
import { AppShell } from '@/components/AppShell';
import { downloadPaperPdf } from '@/lib/pdf';
import type { Assignment } from '@/lib/types';

export default function OutputPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const { paper, status, errorMessage, setCurrentAssignment, setStatus, setPaper, clearPaper } =
    useAssignmentStore();
  const [meta, setMeta] = useState<Assignment | null>(null);
  const [regenerating, setRegenerating] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const paperRef = useRef<HTMLDivElement>(null);

  // Initial load — fetch the assignment unless the store already has a fresh paper.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const a = await getAssignment(id);
        if (cancelled) return;
        setMeta(a);
        setCurrentAssignment(a);
      } catch (e) {
        setStatus('failed', (e as Error).message);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id, setCurrentAssignment, setStatus]);

  async function onRegenerate() {
    if (regenerating) return;
    setRegenerating(true);
    clearPaper();
    setStatus('processing');
    try {
      const result = await regenerateAssignment(id);
      if (result.paper) {
        setPaper(result.paper);
      } else if (result.error || result.status === 'failed') {
        setStatus('failed', result.error ?? 'Regeneration failed');
      }
    } catch (e) {
      setStatus('failed', (e as Error).message);
    } finally {
      setRegenerating(false);
    }
  }

  async function onDownload() {
    if (!paper) return;
    setDownloading(true);
    try {
      await downloadPaperPdf({
        paper,
        dueDate: meta?.dueDate,
        fileName: meta?.title ?? paper.title,
      });
    } catch (e) {
      console.error('[pdf]', e);
      alert(`Could not generate PDF: ${(e as Error).message}`);
    } finally {
      setDownloading(false);
    }
  }

  const isWorking = status === 'queued' || status === 'processing' || regenerating;

  return (
    <AppShell
      title={meta?.title ?? 'Question Paper'}
      subtitle={meta?.subject ?? 'Generated by AI'}
      backHref="/"
    >
      <div className="max-w-4xl mx-auto">
        <AnimatePresence>
          {paper && !isWorking && (
            <motion.div
              key="action-bar"
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.25 }}
              className="no-print mb-4 flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between rounded-card bg-ink-900 text-white px-4 sm:px-5 py-3 text-sm"
            >
              <p className="leading-snug flex items-center gap-2">
                <span className="inline-flex h-5 w-5 rounded-full bg-emerald-500/20 items-center justify-center">
                  <svg viewBox="0 0 24 24" className="h-3 w-3 text-emerald-400" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M5 12l4 4 10-10" />
                  </svg>
                </span>
                Paper ready. Regenerate to get a fresh version, or export as PDF.
              </p>
              <div className="flex gap-2 sm:shrink-0">
                <motion.button
                  whileTap={{ scale: 0.97 }}
                  onClick={onRegenerate}
                  className="inline-flex items-center gap-1.5 rounded-md bg-white/10 hover:bg-white/15 px-3 py-1.5 text-xs font-medium transition"
                  disabled={isWorking}
                >
                  <span>↻</span> Regenerate
                </motion.button>
                <motion.button
                  whileTap={{ scale: 0.97 }}
                  onClick={onDownload}
                  className="inline-flex items-center gap-1.5 rounded-md bg-white text-ink-900 hover:bg-ink-100 px-3 py-1.5 text-xs font-semibold transition"
                  disabled={downloading}
                >
                  {downloading ? 'Preparing…' : '⬇ Download PDF'}
                </motion.button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <AnimatePresence mode="wait">
          {isWorking || !paper ? (
            <motion.div
              key="loading"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.25 }}
            >
              <GeneratingCard
                status={status}
                error={errorMessage}
                isRegen={regenerating}
              />
            </motion.div>
          ) : (
            <motion.div
              key="paper"
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
              className="light-scope rounded-card"
            >
              <QuestionPaper ref={paperRef} paper={paper} dueDate={meta?.dueDate} />
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </AppShell>
  );
}

function GeneratingCard({
  status,
  error,
  isRegen,
}: {
  status: ReturnType<typeof useAssignmentStore.getState>['status'];
  error: string | null;
  isRegen: boolean;
}) {
  if (status === 'failed') {
    return (
      <div className="surface text-center py-16 px-6">
        <div className="h-12 w-12 rounded-full bg-red-50 mx-auto mb-4 flex items-center justify-center text-red-600 text-xl">
          ✕
        </div>
        <h2 className="text-base font-semibold mb-1">Generation failed</h2>
        <p className="text-sm text-ink-500">{error ?? 'Unknown error'}</p>
        <Link href="/" className="btn-outline mt-6 inline-flex">
          Back to dashboard
        </Link>
      </div>
    );
  }

  const stepText = isRegen ? 'Generating a fresh version…' : 'AI is drafting your paper…';

  return (
    <div className="surface relative overflow-hidden">
      <motion.div
        className="absolute top-0 left-0 h-0.5 bg-gradient-to-r from-transparent via-brand-500 to-transparent"
        initial={{ x: '-30%', width: '30%' }}
        animate={{ x: ['-30%', '120%'] }}
        transition={{ duration: 1.6, repeat: Infinity, ease: 'linear' }}
      />
      <div className="px-6 py-12 sm:py-16 flex flex-col items-center text-center">
        <div className="relative h-14 w-14 mb-5">
          <div className="absolute inset-0 rounded-full border-4 border-ink-200" />
          <div className="absolute inset-0 rounded-full border-4 border-ink-900 border-t-transparent animate-spin" />
        </div>
        <h2 className="text-base font-semibold mb-1">{stepText}</h2>
        <p className="text-sm text-ink-500 max-w-sm">
          Usually takes 10–15 seconds. Output is validated against a strict schema before it reaches your screen.
        </p>
        <div className="mt-8 flex items-center gap-3 text-xs text-ink-500 flex-wrap justify-center">
          <StepDot active label="Prompt" />
          <span className="h-px w-6 bg-ink-200" />
          <StepDot active pulse label="AI inference" />
          <span className="h-px w-6 bg-ink-200" />
          <StepDot active label="Validate schema" />
          <span className="h-px w-6 bg-ink-200" />
          <StepDot label="Render paper" />
        </div>
      </div>
    </div>
  );
}

function StepDot({ active, pulse, label }: { active?: boolean; pulse?: boolean; label: string }) {
  return (
    <div className="flex items-center gap-1.5">
      <span
        className={`h-2 w-2 rounded-full ${
          active ? 'bg-ink-900' : 'bg-ink-300'
        } ${pulse ? 'animate-pulse' : ''}`}
      />
      <span className={active ? 'text-ink-800 font-medium' : ''}>{label}</span>
    </div>
  );
}
